#!/bin/bash

# first iteration of this script hardcodes lots of junk ...

# https://github.com/joyent/node-smartdc#cli-usage

#image=`cat images | json -c 'this.name=="ubuntu-14.04" && this.version=="20151005"' 0.id`

if [[ $# -ne 3 ]]; then
    echo "$0 cluster_name instance_role instance_id"
    exit
fi

image='52be84d0-6b06-11e5-a4c0-9f0c52fa368a'
package=`./sdc-json-search packages.json name t4-standard-256M id`

cluster=$1
instance_role=$2
instance_id=$3
hostname="$cluster-$instance_role-$instance_id"
saltmaster=`./sdc-json-search machines.json name $cluster-salt primaryIp`

echo ""
echo "creating $hostname with salt-minion (master: $saltmaster)"
echo ""

sdc-createmachine --image $image --package $package \
  --name $hostname \
  --metadata hostname=$hostname \
  --metadata cluster=$cluster \
  --metadata instance_role=$instance_role \
  --metadata instance_id=$instance_id \
  --metadata saltmaster=$saltmaster \
  --tag hostname=$hostname \
  --tag cluster=$cluster \
  --tag instance_role=$instance_role \
  --tag instance_id=$instance_id \
  --script bootstrap-salt-minion.sh

# update our local JSON files.
echo ""
echo "refreshing our cached SDC JSON files."
./sdc-json-fetch
echo "done!"
