#!/usr/bin/env python
"""
Search for information in Joyant's SDC JSON output.

Requires that `sdc-json-search` was run recently.
"""

from sys import (
  argv,
  exit,
)

if len(argv) != 5:
    print('{} json_file search_field search_field_value field_to_return'.format(argv[0]))
    exit()

json_file          = argv[1]
search_field       = argv[2]
search_field_value = argv[3]
field_to_return    = argv[4]

import json

with open(json_file) as f:
    documents = json.load(f)

for document in documents:
    if document[search_field] == search_field_value:
        print(document[field_to_return])
        break
